[platformio]
default_envs = watchy_v2

[env:watchy_v2]
platform = espressif32@~6.6.0
board = esp32dev
framework = arduino

lib_deps =
    sqfmi/Watchy

lib_ldf_mode = deep+

board_build.partitions = min_spiffs.csv

upload_speed = 115200
monitor_speed = 115200
monitor_port = /dev/ttyACM0
